### ISSUE TITLE
Where is custom patch button ?

### ISSUE THREAD

**Issue by tahaklkt-osxinfo** [ic005k/QtiASL#14]
![image](https://user-images.githubusercontent.com/63608875/118408903-66badc00-b690-11eb-957a-008bd3cf728b.png)

Hello mate. I can't find patch button like maciasl. Where is the patch button ? I need to make battery patch but i can't insert B1B2 method and WECB,RECB etc. . Please develope this feature.

**Comment by m0d16l14n1** [comment]
@tahaklkt-osxinfo use that kext instead of patching your DSDT

https://github.com/1Revenger1/ECEnabler

**Comment by m0d16l14n1** [comment]
DSDT patches are old as hell and don't need them at all in QtiASL at all, as i think. 
Most patches available as SSDTs in acidanthera and dortania docs

**Comment by tahaklkt-osxinfo** [comment]
My laptop is very old. It has Intel Core I5 M430 nVidia GT 330M im using Catalina but ECEnabler isn't worked for me.

**Comment by tahaklkt-osxinfo** [comment]
So im using Clover not Opencore.

**Comment by TheHackGuy** [comment]
@tahaklkt-osxinfo Opencore also works on some old systems. It also has a legacy option.

@tahaklkt-osxinfo I still use acpi patches. I even have my own patches. Many people still use them...
I should really like to see that in the future. (And also some other guys from the Facebook Hackintosh group)

I appreciate your work!

**Comment by ic005k** [comment]
This patching feature won't be available in QtiASL because the patching method is obsolete, it's too old fashioned.
Also, even with very old hardware, whether you use OC or Clover, SSDT hot injection can be used to fix any problems you have, and it's time to phase out the modified DSDT approach.

**Comment by RickiThaDragon** [comment]
I can understand what your saying as far as SSDT Hot Injection being the modern alternative that is suited for most people that are using a Hackintosh System. I respect that and I also understand the depths of the entire topic as well. The SSDT SYSTEM IS THE BEST for the "newbie" or for someone who does not care about the inner workings of the whole thing. But you should know as well as I do that patching a DSDT FOR ones own personal use is a solid method as well and is not obselete by any means. People that are in development with Linix kernel etc emloy it all the time still. I use it all the time. The prerequisite for all of this is that a person needs to know what they are doing. For newbies they should leave it alone completely. And stick with SSDT Because it works out of the box most of the time as long as one can follow instrucions! Anyways I appreciate your effort and your work here. Much respect to You brother. I am grateful for your contribution. If you choose to add new features so be it. If You dont You dont! I aint mad at ya lol! Peace
